version: "3.9"

services:
  todo-be:
    image: todo-be:latest
    depends_on:
      - db
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: postgres
    ports:
      - 8000:8000
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: todo
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
